"""Added file_path column to ToDo

Revision ID: 857c861d1577
Revises: 5a4c5e6b8677
Create Date: 2023-08-26 13:51:48.987132

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '857c861d1577'
down_revision: Union[str, None] = '5a4c5e6b8677'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('file_path', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todos', 'file_path')
    # ### end Alembic commands ###
